FROM mcr.microsoft.com/dotnet/core/sdk:6.0 AS build-env
WORKDIR /app

COPY *.csproj.

RUN dotnet restore

COPY . ./

FROM mcr.microsoft.com/dotnet/core.aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet","FilmApi.dll"]